import type { Instrumento } from './tipos.ts';

// Catálogo de instrumental de research/instrumentos_quirurgicos.csv. La siembra lo copia a la tabla instrumento
// de cada clínica; sirve para corregir los nombres que Chirp transcribe mal (correccion.ts).
export const INSTRUMENTOS: Instrumento[] = [
  { codigo: "INS-001", nombre: "Anoscopio", categoria: "Exploración" },
  { codigo: "INS-002", nombre: "Azul de metileno", categoria: "Medicamentos y Soluciones" },
  { codigo: "INS-003", nombre: "Bandeja de instrumental", categoria: "Recipientes" },
  { codigo: "INS-004", nombre: "Cocas metálicas", categoria: "Recipientes" },
  { codigo: "INS-005", nombre: "Compresas quirúrgicas", categoria: "Insumos" },
  { codigo: "INS-006", nombre: "Cánula de Yankauer con tubo", categoria: "Aspiración" },
  { codigo: "INS-007", nombre: "Dren de Penrose", categoria: "Insumos" },
  { codigo: "INS-008", nombre: "Electrocauterio", categoria: "Electrocirugía" },
  { codigo: "INS-009", nombre: "Estiletes quirúrgicos", categoria: "Exploración" },
  { codigo: "INS-010", nombre: "Gasas quirúrgicas", categoria: "Insumos" },
  { codigo: "INS-011", nombre: "Guantes quirúrgicos", categoria: "Insumos" },
  { codigo: "INS-012", nombre: "Jeringa Asepto", categoria: "Insumos" },
  { codigo: "INS-013", nombre: "Jeringa con marcaína (bupivacaína)", categoria: "Medicamentos y Soluciones" },
  { codigo: "INS-014", nombre: "Jeringa hipodérmica", categoria: "Insumos" },
  { codigo: "INS-015", nombre: "Mango de bisturí", categoria: "Corte" },
  { codigo: "INS-016", nombre: "Mango de bisturí #3", categoria: "Corte" },
  { codigo: "INS-017", nombre: "Pinza de conducto cístico", categoria: "Hemostasia" },
  { codigo: "INS-018", nombre: "Pinzas Babcock", categoria: "Tracción" },
  { codigo: "INS-019", nombre: "Pinzas Baby Mosquito", categoria: "Hemostasia" },
  { codigo: "INS-020", nombre: "Pinzas de Allis", categoria: "Tracción" },
  { codigo: "INS-021", nombre: "Pinzas de campo Backhaus", categoria: "Fijación" },
  { codigo: "INS-022", nombre: "Pinzas de disección Adson con garra", categoria: "Disección" },
  { codigo: "INS-023", nombre: "Pinzas de disección Adson sin garra", categoria: "Disección" },
  { codigo: "INS-024", nombre: "Pinzas de disección con garra", categoria: "Disección" },
  { codigo: "INS-025", nombre: "Pinzas de disección largas", categoria: "Disección" },
  { codigo: "INS-026", nombre: "Pinzas de disección rusa", categoria: "Disección" },
  { codigo: "INS-027", nombre: "Pinzas de disección sin garra", categoria: "Disección" },
  { codigo: "INS-028", nombre: "Pinzas de Pennington", categoria: "Tracción" },
  { codigo: "INS-029", nombre: "Pinzas Foerster (porta-esponja)", categoria: "Tracción" },
  { codigo: "INS-030", nombre: "Pinzas Kelly", categoria: "Hemostasia" },
  { codigo: "INS-031", nombre: "Pinzas Kelly Adson", categoria: "Hemostasia" },
  { codigo: "INS-032", nombre: "Pinzas Kelly Curvas", categoria: "Hemostasia" },
  { codigo: "INS-033", nombre: "Pinzas Kocher", categoria: "Hemostasia" },
  { codigo: "INS-034", nombre: "Pinzas Mosquito", categoria: "Hemostasia" },
  { codigo: "INS-035", nombre: "Pinzas Mosquito Curvas", categoria: "Hemostasia" },
  { codigo: "INS-036", nombre: "Pinzas Rochester-Pean", categoria: "Hemostasia" },
  { codigo: "INS-037", nombre: "Portaagujas", categoria: "Síntesis" },
  { codigo: "INS-038", nombre: "Portaagujas extralargo", categoria: "Síntesis" },
  { codigo: "INS-039", nombre: "Riñonera metálica", categoria: "Recipientes" },
  { codigo: "INS-040", nombre: "Ropa quirúrgica", categoria: "Insumos" },
  { codigo: "INS-041", nombre: "Separador abdominal Balfour", categoria: "Separación" },
  { codigo: "INS-042", nombre: "Separador anal", categoria: "Separación" },
  { codigo: "INS-043", nombre: "Separadores de Deaver", categoria: "Separación" },
  { codigo: "INS-044", nombre: "Separadores de Farabeuf", categoria: "Separación" },
  { codigo: "INS-045", nombre: "Separadores de Richardson", categoria: "Separación" },
  { codigo: "INS-046", nombre: "Separadores de Senn Miller", categoria: "Separación" },
  { codigo: "INS-047", nombre: "Sonda acanalada", categoria: "Exploración" },
  { codigo: "INS-048", nombre: "Suero fisiológico", categoria: "Medicamentos y Soluciones" },
  { codigo: "INS-049", nombre: "Suturas quirúrgicas", categoria: "Síntesis" },
  { codigo: "INS-050", nombre: "Tijeras de Mayo", categoria: "Corte" },
  { codigo: "INS-051", nombre: "Tijeras de Metzenbaum", categoria: "Disección" },
  { codigo: "INS-052", nombre: "Tijeras quirúrgicas largas", categoria: "Corte" },
  { codigo: "INS-053", nombre: "Valvas maleables", categoria: "Separación" },
  { codigo: "INS-054", nombre: "Xilocaína en jalea", categoria: "Medicamentos y Soluciones" },
];
